services:
  splatcal:
    build:
      context: .
    develop:
      watch:
        - action: sync+restart
          path: ./app
          target: /usr/local/splatcal/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./app/package.json
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8035:8080

  db:
    image: mariadb:11
    restart: always
    #volumes:
    #  - ./database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=db
    ports:
      - 8036:80
