version: "2"
services:
  node:
    image: "node:20"
    user: "www-data"
    working_dir: /home/node/app
    env_file: .env
    volumes:
      - /var/www/splatoon-calendar:/home/node/app # first location is on the machine running docker. change this if needed. THIS SHOULD ALWAYS BE SAME AS VOLUME IN NODE - /web
    expose:
      - "8001"
    ports:
      - "8204:8001" # first number is port on the server. change this if needed
    command: "npm start"
  web:
    image: php:8.2-apache
    user: "www-data"
    restart: always
    ports:
      - "8104:80" # first number is port on the server. change this if needed
    volumes:
      - /var/www/splatoon-calendar/web:/var/www/html # first location is on the machine running docker. change this if needed. THIS SHOULD ALWAYS BE SAME AS VOLUME IN NODE + /web
