version: "2"
services:
  node:
    image: "node:20"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - /var/www/splatCal:/home/node/app
    expose:
      - "8081"
    ports: # use if it is necessary to expose the container to the host machine
      - "8204:8001"
    command: "npm start"
  web:
    image: php:8.2-apache    #check the php version you need for your project
    restart: always
    ports:
      - "8104:80"    #this line maps your pc port to the container port
    volumes:
      - /var/www/splatCal/ics:/var/www/html    #this line maps the content of ./html in your pc to the /var/www/html of the container
